### ISSUE TITLE
UCAF - Automated registration process with reflection

### ISSUE THREAD

**Issue by rettichlp** [rettichlp/UnicacityAddon-1.12.2#2]
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Einfacheres arbeiten und anlegen von Events, Modules und Commands

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
Über Annotations sollen Commands, Events und Modules registriert werden
- [x] Annotations anlegen (erledigt durch #1 )
- [x] RegistrationHandler anlegen (erledigt durch #1 )
- [x] ReflectionUtils anlegen (erledigt durch #1 )
- [ ] Funktionalität überprüfen
- [ ] Bug fixes

**Sonstiges**
